ci: use goTestJUnit for run the tests
elastic/ecs-logging-go-zap pull request #28
Opened 2021-01-13 10:48 UTC by kuisathaverat

It uses a setp in the pipeline library to run the tests and generate the JUnit report, this step internally uses [gotestsum](https://github.com/gotestyourself/gotestsum)

2021-01-13 10:49 UTC, v1v approved these changes

2021-01-13 10:54 UTC, apmmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fecs-logging-go-zap-mbp%2FPR-28/detail/PR-28/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fecs-logging-go-zap-mbp%2FPR-28/detail/PR-28/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fecs-logging-go-zap-mbp%2FPR-28/detail/PR-28/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fecs-logging-go-zap-mbp%2FPR-28/detail/PR-28/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://ecs-logging-go-zap_28.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `Pull request #28 opened`

* Start Time: 2021-01-13T10:48:23.637+0000

* Duration: 6 min 2 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 3  |
| Skipped      | 3 |
| Total        | 6   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->





### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fecs-logging-go-zap-mbp%2FPR-28/detail/PR-28/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>

  
  
  
  
  
##### `Checks if running on a Unix-like node`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-go/pipelines/ecs-logging-go-zap-mbp/pipelines/PR-28/runs/1/steps/164/log/?start=0">here</a></li>
<li>Description: <code>Cannot invoke method getAt() on null object</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-01-13T10:54:00.283Z] Collecting importlib-metadata; python_version < "3.8"
[2021-01-13T10:54:00.283Z]   Downloading importlib_metadata-2.1.1-py2.py3-none-any.whl (10 kB)
[2021-01-13T10:54:00.283Z] Collecting importlib-resources; python_version < "3.7"
[2021-01-13T10:54:00.283Z]   Downloading importlib_resources-3.3.1-py2.py3-none-any.whl (26 kB)
[2021-01-13T10:54:00.547Z] Collecting cfgv>=2.0.0
[2021-01-13T10:54:00.547Z]   Downloading cfgv-2.0.1-py2.py3-none-any.whl (7.4 kB)
[2021-01-13T10:54:00.547Z] Collecting nodeenv>=0.11.1
[2021-01-13T10:54:00.547Z]   Downloading nodeenv-1.5.0-py2.py3-none-any.whl (21 kB)
[2021-01-13T10:54:00.807Z] Collecting identify>=1.0.0
[2021-01-13T10:54:00.807Z]   Downloading identify-1.5.12-py2.py3-none-any.whl (97 kB)
[2021-01-13T10:54:00.807Z] Collecting pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32"
[2021-01-13T10:54:00.807Z]   Downloading pathlib2-2.3.5-py2.py3-none-any.whl (18 kB)
[2021-01-13T10:54:00.807Z] Collecting appdirs<2,>=1.4.3
[2021-01-13T10:54:00.807Z]   Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
[2021-01-13T10:54:01.066Z] Collecting distlib<1,>=0.3.1
[2021-01-13T10:54:01.066Z]   Downloading distlib-0.3.1-py2.py3-none-any.whl (335 kB)
[2021-01-13T10:54:01.066Z] Collecting filelock<4,>=3.0.0
[2021-01-13T10:54:01.066Z]   Downloading filelock-3.0.12.tar.gz (8.5 kB)
[2021-01-13T10:54:01.325Z] Collecting contextlib2; python_version < "3"
[2021-01-13T10:54:01.325Z]   Downloading contextlib2-0.6.0.post1-py2.py3-none-any.whl (9.8 kB)
[2021-01-13T10:54:01.325Z] Collecting zipp>=0.5
[2021-01-13T10:54:01.325Z]   Downloading zipp-1.2.0-py2.py3-none-any.whl (4.8 kB)
[2021-01-13T10:54:01.325Z] Collecting configparser>=3.5; python_version < "3"
[2021-01-13T10:54:01.325Z]   Downloading configparser-4.0.2-py2.py3-none-any.whl (22 kB)
[2021-01-13T10:54:01.584Z] Collecting typing; python_version < "3.5"
[2021-01-13T10:54:01.584Z]   Downloading typing-3.7.4.3-py2-none-any.whl (26 kB)
[2021-01-13T10:54:01.584Z] Collecting singledispatch; python_version < "3.4"
[2021-01-13T10:54:01.584Z]   Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl (12 kB)
[2021-01-13T10:54:01.584Z] Collecting scandir; python_version < "3.5"
[2021-01-13T10:54:01.584Z]   Downloading scandir-1.10.0.tar.gz (33 kB)
[2021-01-13T10:54:01.846Z] Building wheels for collected packages: pyyaml, filelock, scandir
[2021-01-13T10:54:01.846Z]   Building wheel for pyyaml (setup.py): started
[2021-01-13T10:54:02.416Z]   Building wheel for pyyaml (setup.py): finished with status 'done'
[2021-01-13T10:54:02.417Z]   Created wheel for pyyaml: filename=PyYAML-5.3.1-cp27-cp27mu-linux_x86_64.whl size=45643 sha256=549eedff32a9f12dc3771c1a684235b72c1a7febce909550d6e601c907d6953b
[2021-01-13T10:54:02.417Z]   Stored in directory: /var/lib/jenkins/workspace/_go_ecs-logging-go-zap-mbp_PR-28/.cache/pip/wheels/d1/d5/a0/3c27cdc8b0209c5fc1385afeee936cf8a71e13d885388b4be2
[2021-01-13T10:54:02.417Z]   Building wheel for filelock (setup.py): started
[2021-01-13T10:54:02.417Z]   Building wheel for filelock (setup.py): finished with status 'done'
[2021-01-13T10:54:02.417Z]   Created wheel for filelock: filename=filelock-3.0.12-py2-none-any.whl size=7576 sha256=e6a1f337baeff660f908570bff19f49247298e0ad73d49fe6858820375184caa
[2021-01-13T10:54:02.417Z]   Stored in directory: /var/lib/jenkins/workspace/_go_ecs-logging-go-zap-mbp_PR-28/.cache/pip/wheels/b9/91/23/b559c1f4fd55056712b3a71cd9cab1dc0089e2232d502ed72e
[2021-01-13T10:54:02.417Z]   Building wheel for scandir (setup.py): started
[2021-01-13T10:54:02.995Z]   Building wheel for scandir (setup.py): finished with status 'done'
[2021-01-13T10:54:02.995Z]   Created wheel for scandir: filename=scandir-1.10.0-cp27-cp27mu-linux_x86_64.whl size=33226 sha256=0095223991154ed0098835df7c136c659b968eb2797d518e8e7b5b5749f7f6c5
[2021-01-13T10:54:02.995Z]   Stored in directory: /var/lib/jenkins/workspace/_go_ecs-logging-go-zap-mbp_PR-28/.cache/pip/wheels/58/2c/26/52406f7d1f19bcc47a6fbd1037a5f293492f5cf1d58c539edb
[2021-01-13T10:54:02.995Z] Successfully built pyyaml filelock scandir
[2021-01-13T10:54:02.995Z] Installing collected packages: futures, pyyaml, aspy.yaml, scandir, six, pathlib2, contextlib2, zipp, configparser, importlib-metadata, typing, singledispatch, importlib-resources, appdirs, distlib, filelock, virtualenv, toml, cfgv, nodeenv, identify, pre-commit
[2021-01-13T10:54:03.935Z] Successfully installed appdirs-1.4.4 aspy.yaml-1.3.0 cfgv-2.0.1 configparser-4.0.2 contextlib2-0.6.0.post1 distlib-0.3.1 filelock-3.0.12 futures-3.3.0 identify-1.5.12 importlib-metadata-2.1.1 importlib-resources-3.3.1 nodeenv-1.5.0 pathlib2-2.3.5 pre-commit-1.21.0 pyyaml-5.3.1 scandir-1.10.0 singledispatch-3.4.0.3 six-1.15.0 toml-0.10.2 typing-3.7.4.3 virtualenv-20.3.1 zipp-1.2.0
[2021-01-13T10:54:03.935Z] Downloading https://files.pythonhosted.org/packages/a4/e3/1f067de470e3a86875ed915438dc3bd781fb0346254f541190a09472b677/virtualenv-16.7.10.tar.gz
[2021-01-13T10:54:03.935Z] Done.
[2021-01-13T10:54:03.935Z] *******************************************************************************
[2021-01-13T10:54:03.935Z] Installing pre-commit to /var/lib/jenkins/workspace/_go_ecs-logging-go-zap-mbp_PR-28/bin/pre-commit
[2021-01-13T10:54:03.935Z] *******************************************************************************
[2021-01-13T10:54:04.310Z] + export PATH=/var/lib/jenkins/workspace/_go_ecs-logging-go-zap-mbp_PR-28/bin:/var/lib/jenkins/workspace/_go_ecs-logging-go-zap-mbp_PR-28/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[2021-01-13T10:54:04.310Z] + pre-commit install --install-hooks
[2021-01-13T10:54:04.310Z] pre- [...]

2021-01-13 11:37 UTC, cachedout approved these changes

2021-01-13 12:45 UTC, simitt approved these changes

2021-01-13 12:46 UTC, simitt requested changes
Tests are actually failing with this change.

2021-01-15 08:49 UTC, kuisathaverat commented
/test

2021-01-15 08:58 UTC, kuisathaverat commented on .ci/Jenkinsfile
> +            goTestJUnit(options: '-v ./...', output: 'build/junit-report.xml')
```suggestion
            goTestJUnit(options: '-v ./...', output: 'junit-report.xml')
```

2021-01-15 09:21 UTC, v1v approved these changes

2021-01-15 16:21 UTC, simitt approved these changes

2021-01-25 11:43 UTC, merged