install ecs
elastic/ecs-logging-go-zap pull request #44
Opened 2022-03-17 09:36 UTC by haibkhn

update install description

2022-03-17 09:39 UTC, apmmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fecs-logging-go-zap-mbp%2FPR-44/detail/PR-44/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fecs-logging-go-zap-mbp%2FPR-44/detail/PR-44/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fecs-logging-go-zap-mbp%2FPR-44/detail/PR-44/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fecs-logging-go-zap-mbp%2FPR-44/detail/PR-44/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-03-17T09:26:18.950Z&rangeTo=2022-03-17T09:46:18.950Z&transactionName=apm-agent-go/ecs-logging-go-zap-mbp/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=cedbfdbfbad381e3d6bbff91519b7929&transactionId=a12522f7840663be)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-17T09:36:18.950+0000


* Duration: 3 min 8 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Pipeline error [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/job/apm-agent-go/job/ecs-logging-go-zap-mbp/job/PR-44/1//console)
  <p>
  This error is likely related to the pipeline itself. Please go to the traditional console output <a href=\"https://apm-ci.elastic.co/job/apm-agent-go/job/ecs-logging-go-zap-mbp/job/PR-44/1//console\">here</a>"
  You will see the error (either a wrong syntax or configuration)
  </p>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-03-18 02:27 UTC, axw requested changes
Thanks @haibkhn! I don't recall why the instructions say to modify go.mod directly, instead of using `go get`. I think using `go get` would be more standard. I'd like to wait for @simitt to chime in.

2022-03-18 02:27 UTC, axw commented on docs/setup.asciidoc
>  Add the package to your `go.mod` file:
```suggestion
Add the package to your `go.mod` file:

[source,go]
----
go get -u go.elastic.co/ecszap
----
```

Also, we should probably remove the "require" code snippet below. WDYT @simitt?

2022-03-18 07:20 UTC, simitt commented
Fully agree, it should be using `go get`. Thanks for the update!

2022-03-22 08:14 UTC, closed without merging